### ISSUE TITLE
How to use "Git Auto Prefix" plugin in IntelliJ

### ISSUE THREAD

**Issue by adbdkb** [thomasrepnik/idea-commit-prefix-plugin#15] opened 2022-02-13 17:32 UTC
I have installed this plugin in my IntelliJ IDEA 2021.3.2 (Community Edition).  What other set-up do I need to do / have so that I can use it?  I tried using the default wrapper as well as changing it to "[ ] -"  but I don't get the jira id when I try to commit a file.

Is there some other set-up required?

I get this error

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/26495406/153767149-576ce12f-8773-453f-8ade-b86b0609d3fc.png">

This will be a very useful plugin if I can get it to work.

Thank you

**Comment by thomasrepnik** [comment] 2022-02-15 17:57
Thank you for your report.
Can you please provide more detailed information?

What is your exact IntelliJ Build? I just tested it with `IC-213.5744.223` and it seems to work.
Can you share the whole Stacktrace? (not just a screenshot)

There are no prerequisites. You just have to enable the IntelliJ Bundled Git Plugin (which is already enabled by default)

I will take a  deeper look as soon as i have the request informations above.

**Comment by adbdkb** [comment] 2022-02-15 18:27
Intellij Build - 

IntelliJ IDEA 2021.3.2 (Community Edition)
Build #IC-213.6777.52, built on January 27, 2022

On
macOS 11.6.1

I have set-up the Wrap Left / Right as blow in the image

<img width="618" alt="GitAutoPrefix_Tools" src="https://user-images.githubusercontent.com/26495406/154123725-6e28c1ac-1d98-49cc-b956-8a3a6dbaf6cb.png">

Today, I am not getting the error I was getting previously, but when I try to commit a file, I do not get the prefix from the branch.   

When I select a file in the Changes in the Commit Tab 

<img width="615" alt="GitAutoPrefix_CommitChanges" src="https://user-images.githubusercontent.com/26495406/154125239-64dd6e60-ec5f-4eb2-8c83-d0dd6501562d.png">

I expect to see the commit message area to be pre-populated with "[data-4124] - ",  but it is blank

<img width="875" alt="GitAutoPrefix_CommitMessageDialogue" src="https://user-images.githubusercontent.com/26495406/154125473-44a243cd-50e1-4f62-a1e1-a35523c3a118.png">


It maybe, that I am missing some set-up

Is there something else I need to set-up in my workspace?

Thanks

**Comment by thomasrepnik** [comment] 2022-02-15 18:44
oh, it seems the issue is your branch name. if i use the same branch name as you then the plugin is not setting any prefix. Can you please test it with a very simple branch like `feature/BUG-455-login` 

i need to analyze what is causing the problem with your branch name.

**Comment by thomasrepnik** [comment] 2022-02-15 18:59
How did you create your branch? Did you use the Jira link provided in the UI?
![image](https://user-images.githubusercontent.com/47736416/154130142-75ac06da-7277-4816-af0e-5375f9323b28.png)

**Comment by adbdkb** [comment] 2022-02-15 19:31
Let me try with a smaller branch name.  I think I created the branch from jira.  But initially, if the branch name had Capital letters, the automated Jenkins  build used to fail for that branch, so I think I made the Jira key, as small case.  Could that be a problem with the branch name or the length?


Update
======

I created a new branch from Jira - keeping the case and smaller branch name, but still don't get the expected jira id in the commit message

<img width="1748" alt="GitAutoPrefix_BranchNameTest" src="https://user-images.githubusercontent.com/26495406/154150668-9dcb5dbe-61af-4f4c-95fb-033a5a2dd5c2.png">


Thanks

**Comment by thomasrepnik** [comment] 2022-02-15 21:47
Please be aware that this plugin only supports branches created with the Jira Link. If you create them by your own you need to make sure that you create the branch name **exactly** the same as Jira would.

Your problem should be gone if your branch name was named with capital issue identifier like `feature/DATA-4214-ab-CEP3.0-Transition-polling`. This is also the way Jira would create it.

I will close the Issue for now, as it is working as designed. If the plugin still does not work, please feel free to let me know.

**Closed as completed by thomasrepnik** 2022-02-15 21:47 UTC
